### ISSUE TITLE
Native "GetOutputCount" was not found

### ISSUE THREAD

**Issue by Cruze03** [oylsister/sm-ext-outputinfo#1]
In your compiled extension, GetOutputCount native was not found. Any fix?

**Comment by Cruze03** [comment]
nvm, I'm an idiot. Everything works! Thanks for this <3

**Comment by oylsister** [comment]
some of the natives is included in outputinfo_botox.inc

**Comment by KvN069** [comment]
> nvm, I'm an idiot. Everything works! Thanks for this <3

How did you fix it?

**Comment by oylsister** [comment]
> some of the natives is included in outputinfo_botox.inc

**Comment by oylsister** [comment]
> > nvm, I'm an idiot. Everything works! Thanks for this <3
> How did you fix it?
> some of the natives is included in outputinfo_botox.inc

**Comment by oylsister** [comment]
> How did you fix it?



> some of the natives is included in outputinfo_botox.inc
